
server:
  contextPath: /hrdemo
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat


spring:
  # Allow Thymeleaf templates to be reloaded at dev time
  thymeleaf.cache: false

  profiles:
    #profile for repository
#    active: mem
    active: spring-data-jpa

  datasource:
    # MySQL Settings
#    platform: mysql
#    url: jdbc:mysql://localhost/test
#    username: dbuser
#    password: dbpass
#    driverClassName: com.mysql.jdbc.Driver

    # HSQL Settings
    platform: hsqldb
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:hrdemo
#    url: jdbc:hsqldb:hsql://localhost/hrdemo
    username: sa
    password:

    # initialization
    #schema: "classpath*:schema.sql"
    #data: "classpath*:data.sql"

# to avoid initialization done by hibernate
  jpa.hibernate.ddl-auto: none
